spring:
  application:
    name: grpc-client
server:
  port: 8082
grpc:
  client:
    grpc-server:
      address: 'static://127.0.0.1:8899'
      enable-keep-alive: true
      keep-alive-without-calls: true
      negotiation-type: plaintext
